# -*- org-export-babel-evaluate: nil -*-
# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+title: *Relatório do 1º Trabalho Prático*
#+options: toc:nil author:nil
#+tags: noexport(n) ignore(i)
#+language: pt-br

#+latex_class: article
#+latex_class_options: [twocolumn, a4paper]

#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage[blocks]{authblk}
#+latex_header: \usepackage{titling}
#+latex_header: \usepackage{palatino}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{lipsum}
#+latex_header: \usepackage[brazilian]{babel}
#+latex_header: \renewcommand\Authsep{\\}
#+latex_header: \renewcommand\Authand{\\}
#+latex_header: \renewcommand\Authands{\\}
#+latex_header: \author{Felipe Colombelli}
#+latex_header: \author{Giovanna Lazzari Miotto}
#+latex_header: \author{Henrique Corrêa Pereira da Silva}
#+latex_header: \affil[1]{Instituto de Informática\\Universidade Federal do Rio Grande do Sul}
#+latex_header: \affil[ ]{\normalsize\texttt{\{fcolombelli, glmiotto, hcpsilva\}@inf.ufrgs.br}}

#+latex_header: \setlength{\droptitle}{-1.2cm}
#+latex_header: \usemintedstyle{manni}

* Resumo                                                             :ignore:

#+begin_abstract
Neste trabalho nós implementamos e validamos 3 algoritmos de aprendizado de
máquina que controlam um carro numa corrida, tomando decisões a partir de seus
sensores ao mundo externo. Nossas implementações foram bem sucedidas, etc
etc. No melhor caso, o algoritmo etc concluiu seu treinamento em etc iterações e
chegou a pontuar em média etc pontos em todas as pistas.
#+end_abstract

* Sumário                                                            :ignore:

#+toc: headlines 5

* Introdução

\lipsum[1-1]

* Algoritmos Implementados

Dentre os variados algoritmos que nos foram apresentados tanto em aula quanto
nas publicações que versam sobre o estado da arte, escolhemos os sequintes:

- CMA-ES
- Algoritmos Genéticos
- Hill Climbing

Esse grupo de algoritmos, acreditamos nós, é uma gama que tem tanto abordagens
clássicas quanto modernas, o que para a comparação futura nos pareceu
interessante.

** CMA-ES

Leve preâmbulo de explicação.

Snippet do código.

Comentários sobre a dificuldade de implementação.

** Algoritmos Genéticos

Algoritmos Genéticos correspondem a um grupo de metaheurísticas que aplicam
analogias provindas da biologia e da solução natural para selecionar indivíduos
mais aptos em determinada situação. Por serem algoritmos clássicos e por
possuirem diversas variações e abordagens únicas na literatura, acreditamos que
seriam um tópico interessante de se aplicar no trabalho prático.

# explicar cada escolha, o que é o individuo, como geramos a pop, etc
# uma sessão pra cada algoritmo é pouco :c

#+latex: \begin{listing*}
#+attr_latex: :options fontsize=\scriptsize
#+begin_src python :tangle no
def genetic_algorithm(
        self, weights, population_size=150,
        elitism=0.15):
    roulette = 0.1
    mutation_rate = 0.2
    max_generations = 1
    max_same_best = 10
    perturbation_range = 0.5

    # ITS TOO BIG
    # HELPS

    return population[np.argmax(fitness)],
           max(fitness)
#+end_src
#+latex: \end{listing*}

Comentários sobre a dificuldade de implementação.

** Hill Climbing

Leve preâmbulo de explicação.

Snippet do código.

Comentários sobre a dificuldade de implementação.

** Simulated Annealing

Leve preâmbulo de explicação.

Snippet do código.

Comentários sobre a dificuldade de implementação.


* Desenvolvimento

Sendo um trabalho primeiramente de implementação, tentamos colocar em primeiro
lugar os interesses e curiosidades do grupo na escolha dos algoritmos.

** Estratégia de Desenvolvimento

\lipsum[1-1]

** Episódio e Sessões de Treinamento

\lipsum[2-2]

** Features Escolhidas

\lipsum[3-3]

* Resultados

\lipsum[3-3]

** Visualizações

# só placeholder mesmo, o org-mode ja arruma o width automaticamente
\includegraphics[width=\linewidth]{example-image-a}

** Conclusões
